trigger:
- main

parameters:
  - name: azureServiceConnection
    type: string
    default: arm
  - name: resourceGroupName
    type: string
    default: userdbrg
  - name: location
    type: string
    default: australiaeast
  - name: dbName
    type: string
    default: usersdbnz
  - name: dbCatalogName
    type: string
    default: UsersDatabase
  - name: dbUsername
    type: string
    default: dbadmin

variables:
  templateFile: 'main.bicep'
  dbConnectionString: 'Server=tcp:${{ parameters.dbName }}.database.windows.net,1433;Initial Catalog=${{ parameters.dbCatalogName }};Persist Security Info=False;User ID=${{ parameters.dbUsername }};Password=$(DBPasswordSecret);MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'

pool: 'SelfHostedPool'

steps:
# Create Azure resources
- task: AzureCLI@2
  inputs:
    azureSubscription: '${{ parameters.azureServiceConnection }}'
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      echo dbConnectionString


      az --version
      $rgExists = az group exists --name ${{ parameters.resourceGroupName }}
      if ($rgExists)
      {
        az group delete --name ${{ parameters.resourceGroupName }}
      }
      az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }}      
      az deployment group create `
        --resource-group ${{ parameters.resourceGroupName }} `
        --template-file $(templateFile) `
        --parameters location='${{ parameters.location }}' `
        --parameters sqlServerName='${{ parameters.dbName }}' `
        --parameters adminUsername='${{ parameters.dbUsername }}' `
        --parameters adminPassword='$(DBPasswordSecret))}' `
        --parameters sqlDatabaseName='${{ parameters.dbCatalogName }}' 
